executable              = plotHLT_job.sh
output                  = /afs/cern.ch/work/h/hhua/HLT_QDM/CMSSW_12_4_0_pre1/src/HLT-DQM-HTCondor/hua/jobs/logs/plotHLT.out
error                   = /afs/cern.ch/work/h/hhua/HLT_QDM/CMSSW_12_4_0_pre1/src/HLT-DQM-HTCondor/hua/jobs/logs/plotHLT.err
log                     = /afs/cern.ch/work/h/hhua/HLT_QDM/CMSSW_12_4_0_pre1/src/HLT-DQM-HTCondor/hua/jobs/logs/plotHLT.log
+JobFlavour             = "workday"
#use_x509userproxy = true
#x509userproxy = /afs/cern.ch/user/h/hhua/.x509up_117245
#should_transfer_files   = YES
#when_to_transfer_output = ON_EXIT
queue