arguments               = $(Process)
executable              = /afs/cern.ch/work/h/hhua/HLTStudy/TOPHLTeff/jobs/Moun2022/singleJob.sh
output                  = /afs/cern.ch/work/h/hhua/HLTStudy/TOPHLTeff/jobs/Moun2022//logs/$(Process).out
error                   = /afs/cern.ch/work/h/hhua/HLTStudy/TOPHLTeff/jobs/Moun2022//logs/$(Process).err
log                     = /afs/cern.ch/work/h/hhua/HLTStudy/TOPHLTeff/jobs/Moun2022//logs/log.log
+JobFlavour             = "workday"
use_x509userproxy = true
x509userproxy = /afs/cern.ch/user/h/hhua/.x509up_117245
should_transfer_files   = YES
when_to_transfer_output = ON_EXIT
queue 983  
